version: '3'

services:
    db:
        image: mysql:8.0
        volumes: 
            - database:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: pdc
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ONETIME_PASSWORD: "yes"
        ports:
            - "3306:3306"
        expose: 
            - "3306"
        command: --default-authentication-plugin=mysql_native_password

volumes: 
    database: